### ISSUE TITLE
Could not find driver

### ISSUE THREAD

**Issue by lenerdz** [zball/FOSREST-User-OAuth-Skeleton#6]
I'm having an error message when executing "php bin/console doctrine:database:create"

it says:

`18:04:40 ERROR     [console] Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: could not find driver" ["error" => Doctrine\DBAL\Exception\DriverException {trace: { …} …},"command" => "doctrine:database:create","message" => "An exception occured in driver: could not find driver"] []
18:04:41 ERROR     [console] Command "doctrine:database:create" exited with code "1" ["command" => "doctrine:database:create","code" => 1] []

  [Doctrine\DBAL\Exception\DriverException]
  An exception occured in driver: could not find driver

  [Doctrine\DBAL\Driver\PDOException]
  could not find driver

  [PDOException]
  could not find driver

doctrine:database:create [--shard SHARD] [--connection [CONNECTION]] [--if-not-exists] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>`

what happened? Help me

**Comment by njr03304** [comment]
Sounds like missing php-mysqlnd

**Comment by lenerdz** [comment]
I changed some configurations and the error message changed.
Now it says:

19:27:08 ERROR     [console] Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [2002] Nenhuma conexo pde ser feita porque a mquina de destino as recusou ativamente.
" ["error" => Doctrine\DBAL\Exception\ConnectionException {trace: { …} …},"command" => "doctrine:database:create","message" => b"An exception occured in driver: SQLSTATE[HY000] [2002] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.\r\n"] []
19:27:08 ERROR     [console] Command "doctrine:database:create" exited with code "1" ["command" => "doctrine:database:create","code" => 1] []


  [Doctrine\DBAL\Exception\ConnectionException]
  An exception occured in driver: SQLSTATE[HY000] [2002] Nenhuma conexo pde ser feita porque a mquina de destino a
  s recusou ativamente.



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [2002] Nenhuma conexo pde ser feita porque a mquina de destino as recusou ativamente.



  [PDOException]
  SQLSTATE[HY000] [2002] Nenhuma conexo pde ser feita porque a mquina de destino as recusou ativamente.


doctrine:database:create [--shard SHARD] [--connection [CONNECTION]] [--if-not-exists] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

"Nenhuma conexo pde ser feita porque a mquina de destino as recusou ativamente." basically stands for "Connection Refused"

**Comment by zball** [comment]
try running- php bin/symfony_requirments it should show you all your missing for your environment

**Comment by zball** [comment]
connection refused may also be because you dont have your parameters set properly in app/consifg/paramters.ini.  Make sure your mysql params are correct.

**Comment by lenerdz** [comment]
Symfony Requirements Checker
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> PHP is using the following php.ini file:
  C:\php\php.ini

> Checking Symfony requirements:
  ...........................WWW......


 [OK]
 Your system is ready to run Symfony projects


Optional recommendations to improve your setup
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 * intl extension should be available
   > Install and enable the intl extension (used for validators).

 * a PHP accelerator should be installed
   > Install and/or enable a PHP accelerator (highly recommended).

 * realpath_cache_size should be at least 5M in php.ini
   > Setting "realpath_cache_size" to e.g. "5242880" or "5M" in
   > php.ini* may improve performance on Windows significantly in some
   > cases.


Note  The command console could use a different php.ini file
~~~~  than the one used with your web server. To be on the
      safe side, please check the requirements from your web
      server using the web/config.php script.

**Comment by lenerdz** [comment]
the app/config/parameters.ini:

# This file is auto-generated during the composer install
parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: youruser
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt

**Comment by zball** [comment]
from cli can you: "mysql -u root -p" and get a mysql terminal?

**Comment by lenerdz** [comment]
thanks, zball... MySQL port was different :3
